import uuid
from django.db import models
from django.core.validators import MinValueValidator, MaxValueValidator


class StudentOnboardingRecord(models.Model):
    """
    Django ORM Model representing student onboarding records.
    Fields enforce explicit length constraints and binary DCYN boolean flags.
    """

    student_identification_number = models.UUIDField(
        primary_key=True,
        default=uuid.uuid4,
        editable=False,
        help_text="Universally Unique Identifier Version 4 assigned to the student.",
    )
    student_full_name = models.CharField(
        max_length=100,
        blank=False,
        null=False,
        help_text="Complete legal name of the student.",
    )
    student_age = models.IntegerField(
        validators=[
            MinValueValidator(3, message="Student age must be at least 3 years."),
            MaxValueValidator(18, message="Student age cannot exceed 18 years."),
        ],
        help_text="Current age of the student expressed in complete years.",
    )
    guardian_email_address = models.EmailField(
        max_length=254,
        blank=False,
        null=False,
        help_text="Primary electronic mail address of the parent or legal guardian.",
    )
    completed_medical_assessment = models.BooleanField(
        default=False,
        help_text="Binary flag indicating if formal learning evaluation is finalized.",
    )
    requires_learning_support_assistant = models.BooleanField(
        default=False,
        help_text="Binary flag indicating if dedicated assistance is requested.",
    )
    is_eligible_for_onboarding = models.BooleanField(
        default=False,
        help_text="Output flag generated by the Data/Code Yes-No (DCYN) logic engine.",
    )
    created_at = models.DateTimeField(
        auto_now_add=True,
        help_text="Timestamp when the onboarding payload was processed.",
    )

    class Meta:
        db_table = "student_onboarding_records"
        ordering = ["-created_at"]
        verbose_name = "Student Onboarding Record"
        verbose_name_plural = "Student Onboarding Records"

    def __str__(self):
        return f"{self.student_full_name} ({self.student_identification_number})"
